name: 'yq'
description: 'Run a yq command'
inputs:
  expression:
    description: 'yq expression to eval'
    required: true
  file:
    description: 'path to the file yq should modify'
    required: true
runs:
  using: 'docker'
  image: 'mikefarah/yq:4'
  args:
  - eval
  - -i
  - '${{ inputs.expression }}'
  - ${{ inputs.file }}